# Generated by Django 5.0.3 on 2024-03-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_alter_word_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='transcription',
            field=models.CharField(default='no translation', max_length=100),
        ),
    ]
